In [2]:
import scipy.io as sio
import numpy as np

In [3]:
a=np.zeros((595,2))

In [5]:
a[:,0]=[i for i in range(1,596)]

In [7]:
a[:,1]=[i for i in range(1,596)]

In [12]:
sum(sum(a))

354620.0

In [31]:
q,k = a.shape

In [32]:
q

595

In [33]:
k

2

In [34]:
len(np.intersect1d(a[594,0],a[594,1]))

1

In [35]:
 len(np.intersect1d(a[594,0],a[594 + 1,1]))

IndexError: index 595 is out of bounds for axis 0 with size 595

In [36]:
len(np.intersect1d(a[594,0],a[593,1]))

0

In [41]:
featidx=a
d=595

In [43]:
r

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 1., ..., 1., 1., 0.],
       [0., 0., 1., ..., 1., 1., 0.],
       ...,
       [0., 0., 0., ..., 1., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [47]:
r

array([[0., 0.],
       [0., 0.]])

In [54]:
A = np.true_divide(np.subtract(r, (k**2/d)),(k-(k**2/d)))

In [57]:
sum(sum(A))

87163.48650927353

array([[-0.00672269, -0.00672269, -0.00672269, ..., -0.00672269,
        -0.00672269, -0.00672269],
       [-0.00672269,  0.99327731,  0.99327731, ...,  0.99327731,
         0.99327731, -0.00672269],
       [-0.00672269, -0.00672269,  0.99327731, ...,  0.99327731,
         0.99327731, -0.00672269],
       ...,
       [-0.00672269, -0.00672269, -0.00672269, ...,  0.99327731,
         0.99327731, -0.00672269],
       [-0.00672269, -0.00672269, -0.00672269, ..., -0.00672269,
         0.99327731, -0.00672269],
       [-0.00672269, -0.00672269, -0.00672269, ..., -0.00672269,
        -0.00672269, -0.00672269]])

In [48]:
q,k = featidx.shape
#q = size(featidx,1);
#q=num_methods
r = np.zeros((q,q))
for n in range(1,q-1):
    for m in range(n,q-1):
        r[n,m] = len(np.intersect1d(featidx[n,0],featidx[n,1])) + len(np.intersect1d(featidx[n,0],featidx[n + 1,1])) + len(np.intersect1d(featidx[n,0],featidx[n-1,1]))
A = np.divide((r-(k^2/d)),(k-(k^2/d)))
S = 2*sum(sum(A))/(q*(q-1))

TypeError: unsupported operand type(s) for ^: 'int' and 'float'

In [58]:
def kuncheva_stability(featidx,d):
    q,k = featidx.shape
    #q = size(featidx,1);
    #q=num_methods
    r = np.zeros((q,q))
    for n in range(1,q-1):
        for m in range(n,q-1):
            r[n,m] = len(np.intersect1d(featidx[n,0],featidx[n,1])) + len(np.intersect1d(featidx[n,0],featidx[n + 1,1])) + len(np.intersect1d(featidx[n,0],featidx[n-1,1]))
    A = np.true_divide(np.subtract(r, (k**2/d)),(k-(k**2/d)))
    S = 2*sum(sum(A))/(q*(q-1))
    return(S)

In [59]:
kuncheva_stability(a,595)

0.49324328160752356

In [ ]:
def get_stability():
    

In [5]:
from nilearn.nilearn.plotting import plot_stat_map, show
from nilearn.nilearn.image import index_img
from nilearn.nilearn.image.image import mean_img

ImportError: No module named 'nibabel'. Module "nibabel" could not be found. Please install it properly to use nilearn.

In [3]:
# Reverse masking, and display the corresponding map
components = nifti_masker.inverse_transform(components_masked)

# Visualize results
from nilearn.plotting import plot_stat_map, show
from nilearn.image import index_img
from nilearn.image.image import mean_img

# calculate mean image for the background
mean_func_img = mean_img(func_filename)

plot_stat_map(index_img(components, 0), mean_func_img,
              display_mode='y', cut_coords=4, title="Component 0")

show()


In [ ]:
nilearn.

In [2]:
Data=sio.loadmat('LHmat1.mat')

In [3]:
Data

{'LHmat1': array([[0.0176007 , 0.14745   , 0.16505   , ..., 0.0154293 , 0.0154293 ,
         0.27216   ],
        [0.0152086 , 0.0855809 , 0.10079   , ..., 0.0132863 , 0.0132863 ,
         0.19974   ],
        [0.0790664 , 0.0795773 , 0.158644  , ..., 0.0191432 , 0.0191432 ,
         0.139108  ],
        ...,
        [0.0868267 , 0.143509  , 0.0566822 , ..., 0.0345723 , 0.0345723 ,
         0.14606   ],
        [0.0636159 , 0.173055  , 0.109439  , ..., 0.0092263 , 0.0092263 ,
         0.269375  ],
        [0.0450063 , 0.124946  , 0.0799401 , ..., 0.00283139, 0.00283139,
         0.206063  ]]),
 '__globals__': [],
 '__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Thu May 17 18:22:41 2018',
 '__version__': '1.0'}

In [4]:
X=Data['LHmat1']

In [5]:
X = X.astype(float)

In [6]:
labels=sio.loadmat('./labels77.mat')

In [7]:
y=labels['labels']

In [8]:
y=y[:, 0]

In [9]:
from sklearn.model_selection import KFold
from sklearn import svm
from sklearn.metrics import accuracy_score
from skfeature.function.similarity_based import reliefF

In [12]:

# split data into 5 folds
kf5=KFold(n_splits=5,shuffle=True)
# Number of selected features (top k ranked features)

#top K selected features varying from 10 to 100 (with a step size of 10 features)
num_fea = [i for i in range(10,110,10)]
clf = svm.LinearSVC()    # linear SVM
correct=0
accuracy=[]
#ss = cross_validate(n_samples, n_folds=5, shuffle=True)

In [13]:
def relief_FS(X_train,y_train,k):
    score=reliefF.reliefF(X_train,y_train,k)
    idx=reliefF.feature_ranking(score)
    return(idx,score)

In [14]:
#laplacian
from skfeature.function.similarity_based import lap_score
from skfeature.utility import construct_W
def lap_score_FS(X):
    # construct affinity matrix
    kwargs_W = {"metric": "euclidean", "neighbor_mode": "knn", "weight_mode": "heat_kernel", "k": 5, 't': 1}
    W = construct_W.construct_W(X, **kwargs_W)
    # obtain the scores of features
    score = lap_score.lap_score(X, W=W)
    idx=lap_score.feature_ranking(score)
    return(idx,score)

In [28]:
X.shape

(77, 595)

In [45]:
sum(np.array([1,2,3]))

6

In [32]:
for i in range(4):
    print(i)

0
1
2
3


In [63]:
def training(cv,k,FS_method,X,y):
    accuracy=[]
    featureranking=[]
    featureweight=[]
    normalized_rank_=[]
    for train_index, test_index in cv.split(X):
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]
        if FS_method==reliefF:
            idx,score=relief_FS(X_train,y_train,k)
        elif FS_method==lap_score:
            idx,score=lap_score_FS(X)
        
        selected_features = X[:, idx[0:k]]
        #featureweight=score[0:k]
        # train a classification model with the selected features on the training dataset
        clf.fit(selected_features[train_index], y[train_index])  # predict the class labels of test data
        y_predict = clf.predict(selected_features[test_index])
        normalized_rank=sum(score[0:k])/77
        normalized_rank_.append(normalized_rank)
        featureranking.extend([idx[0:k]])
        featureweight.extend([score[0:k]])
        # obtain the classification accuracy on the test data
    #featureranking=idx[0:k]
    #featureweight=score[0:k]
    accuracy=float(correct)/cv.get_n_splits(X)
    #return(np.array(featureranking),accuracy,np.array(featureweight))
    return(accuracy,np.array(normalized_rank_),featureranking,featureweight)

In [62]:
accuracy,normalized_rank,feature=training(kf5,10,reliefF,X,y)

array([ 0.00212505, -0.00205392, -0.00045035, -0.00046671, -0.00442509])

In [27]:
featureweight.shape

(10,)

In [18]:
features.shape

(77, 10)

In [33]:
ranking_.shape

(5, 589)

In [ ]:
import scipy.io as sio

In [3]:
data=sio.loadmat('./Data_77subjects/LH77subjects/subject10.mat')

In [6]:
X=data['A']

In [7]:
len(X)

35

In [9]:
X.shape

(35, 35, 4)

In [14]:
import numpy as np

### The Tensor is multi-view morphological brain connectivity

### Including 4  cortical thickness network/attributes: sulcal depth network, average curvature network,and principal curvature network

In [17]:
new_X=np.transpose(X)

In [28]:
new_X[3].min()

0.0

In [29]:
new_X[3].max()

0.0995872

In [25]:
Mean_cortical_thickness=new_X[1]

In [30]:
Mean_sulcal_depth=new_X[3]

In [ ]:
from nilearn.nilearn import plotting

In [ ]:
import nilearn